# Generated by Django 6.1 on 2026-08-14 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('terminal', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('programado', 'Programado'), ('embarque', 'Embarque'), ('salida', 'Salida'), ('retrasado', 'Retrasado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('departure_time', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vuelos', to='airport.gate')),
            ],
        ),
    ]
